### ISSUE TITLE
Also full text content

### ISSUE THREAD

**Issue by carcam** [CatPointer/joomla-algolia#3]
https://github.com/CatPointer/joomla-algolia/blob/f9e55285aa781b2d9d4ea29c2e80339e66b8ebce/extensions/libraries/algolia/src/Content/IndexableArticle.php#L38

Shouldn't it also index the full text article? Otherwise the search is always just for introtext...

**Comment by phproberto** [comment]
Indexing full text causes `Record is too big` errors because it's too much data to index. It's not a recommended practice and will cause a lot of issues coming into this direction. 

Index everything all the time is not a recommended practice. Users need to understand that they need to invest time defining their data structure.

References:
* [Algolia's FAQ: Is there a size limit for my index/records? ](https://www.algolia.com/doc/faq/basics/is-there-a-size-limit-for-my-index-records/)
* [Algolia's DOCs: Structure/Format your Data](https://www.algolia.com/doc/guides/indexing/structuring-your-data/)
